ALTER SESSION SET CONTAINER = xepdb1;

-- DROP OLD TABLESPACES IF EXIST
drop TABLESPACE PHOTOMANAGER_STD INCLUDING CONTENTS;
drop TABLESPACE PHOTOMANAGER_IND INCLUDING CONTENTS;
drop TABLESPACE PHOTOMANAGER_STD_L INCLUDING CONTENTS;
drop TABLESPACE PHOTOMANAGER_IND_L INCLUDING CONTENTS;
drop TABLESPACE PHOTOMANAGER_AUD_L INCLUDING CONTENTS;

-- CREATE TABLESPACES
create TABLESPACE PHOTOMANAGER_STD_L DATAFILE 'PHOTOMANAGER_STD_FILE' SIZE 10 M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 1000M;
create TABLESPACE PHOTOMANAGER_IND_L DATAFILE 'PHOTOMANAGER_IND_FILE' SIZE 10 M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 1000M;
create TABLESPACE PHOTOMANAGER_AUD_L DATAFILE 'PHOTOMANAGER_AUD_FILE' SIZE 10 M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 1000M;

-- DROP OLD USER IF EXISTIS
drop user "PHOTOMANAGER" CASCADE;

-- CREATE USER
CREATE USER PHOTOMANAGER IDENTIFIED BY start ;

-- ROLES
GRANT "CONNECT" TO PHOTOMANAGER;
ALTER USER PHOTOMANAGER DEFAULT ROLE "CONNECT";

-- SET TABLESPACES
ALTER USER "PHOTOMANAGER" DEFAULT TABLESPACE "PHOTOMANAGER_STD_L" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "PHOTOMANAGER" QUOTA UNLIMITED ON PHOTOMANAGER_STD_L;
ALTER USER "PHOTOMANAGER" QUOTA UNLIMITED ON PHOTOMANAGER_IND_L;
ALTER USER "PHOTOMANAGER" QUOTA UNLIMITED ON PHOTOMANAGER_AUD_L;

-- SYSTEM PRIVILEGES
GRANT CREATE TABLE TO "PHOTOMANAGER" ;
GRANT CREATE SEQUENCE TO "PHOTOMANAGER" ;
