INSERT INTO PERSON (ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,VERSION,REPLICATION_ID,ANMERKUNG,IVV_MIGRATION_ID,KDS_ID) values ('27058','flyway',current_timestamp,'flyway',current_timestamp,'1','flyway', '',to_timestamp('1998-12-20-00.00.00.000000','RRRR-MM-DD-HH24.MI.SS.FF6'),null);

INSERT INTO JURISTISCHE_PERSON (ART,KURZBEZEICHNUNG,LANGBEZEICHNUNG,NAME,ID) values ('JA','XXX','Justizanstalt X','Justizanstalt X','27058');

INSERT INTO BEHOERDE (BEHOERDENART,BUNDESLAND,EINLIEFERUNGSBEHOERDE,INAKTIV,STAAT,STRAFSTELLENDE_BEHOERDE,ID,BEHOERDENCODE) values (null,null,'0','0',null,'0','27058','058');

INSERT INTO JUSTIZANSTALT (ID,GERICHT_UID) values ('27058','059');


INSERT INTO PERSON (ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,VERSION,REPLICATION_ID,ANMERKUNG,IVV_MIGRATION_ID,KDS_ID) values ('27068','flyway',current_timestamp,'flyway',current_timestamp,'1','flyway68', '',to_timestamp('1998-12-20-00.00.00.000001','RRRR-MM-DD-HH24.MI.SS.FF6'),'12345');

INSERT INTO JURISTISCHE_PERSON (ART,KURZBEZEICHNUNG,LANGBEZEICHNUNG,NAME,ID) values ('JA','KDS ','Justizanstalt KDS','Justizanstalt KDS','27068');

INSERT INTO BEHOERDE (BEHOERDENART,BUNDESLAND,EINLIEFERUNGSBEHOERDE,INAKTIV,STAAT,STRAFSTELLENDE_BEHOERDE,ID,BEHOERDENCODE) values (null,null,'0','0',null,'0','27068','068');

INSERT INTO JUSTIZANSTALT (ID,GERICHT_UID) values ('27068','059');


INSERT INTO ADRESSE (ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION, REPLICATION_ID, ADRESSART, BEZEICHNUNG, GILT_BIS, GILT_VON, IVV_MIGRATION_ID, ORT, PLZ, STAAT, STRASSE, PERSON_ID) values ('785534','TransferKDSSchedueler',        current_timestamp,        'TransferKDSSchedueler',        current_timestamp,        0,        'replid432',        null,        'Bezeichnung Abgabestelle',        to_date('8888-12-20','RRRR-MM-DD'),        to_date('1998-12-20','RRRR-MM-DD'),        current_timestamp,        'Zwettl',        '3910',        'OESTERREICH',        'Hauptplatz 1',        '27068');


INSERT INTO TELEKOMMUNIKATION (ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION, REPLICATION_ID, BERUFLICH, BEZEICHNUNG, GILT_BIS, GILT_VON, IVV_MIGRATION_ID, KENNUNG, PRIVAT, TELEKOMMUNIKATIONSART, PERSON_ID) values ('785534','TransferKDSSchedueler',        current_timestamp,        'TransferKDSSchedueler',        current_timestamp,        0,        'replid432',        0,        'Bezeichnung Abgabestelle',        to_date('8888-12-20','RRRR-MM-DD'),        to_date('1998-12-20','RRRR-MM-DD'),        current_timestamp,        '1234534324532',        '0',        'TELEFON',     '27068');


INSERT INTO PERSON (ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,VERSION,REPLICATION_ID,ANMERKUNG,IVV_MIGRATION_ID,KDS_ID) values ('27087','flyway',current_timestamp,'flyway',current_timestamp,'1','flyway87', '',to_timestamp('1998-12-20-00.00.00.000002','RRRR-MM-DD-HH24.MI.SS.FF6'),'12387');
INSERT INTO JURISTISCHE_PERSON (ART,KURZBEZEICHNUNG,LANGBEZEICHNUNG,NAME,ID) values ('AMS','YYY','AMS Y','AMS YYYYYYYYY','27087');
INSERT INTO BEHOERDE (BEHOERDENART,BUNDESLAND,EINLIEFERUNGSBEHOERDE,INAKTIV,STAAT,STRAFSTELLENDE_BEHOERDE,ID,BEHOERDENCODE) values (null,null,'0','0',null,'0','27087','087');

